# set-option -sa terminal-overrides ",xterm*:Tc"
set -g mouse on
set -g default-terminal "tmux-256color"
# set -g default-terminal "screen-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

bind f display-popup -E -w 80 -h 30 "~/.cargo/bin/claude-tmux"

# bind -n H previous-window
# bind -n L next-window
bind s choose-tree -Z
bind -n M-h previous-window
bind -n M-l next-window
bind -n M-y select-window -t :=1
bind -n M-u select-window -t :=2
bind -n M-i select-window -t :=3
bind -n M-o select-window -t :=4
bind -n M-p select-window -t :=5
bind y select-window -t :=1
bind u select-window -t :=2
bind i select-window -t :=3
bind o select-window -t :=4
bind -n C-M-h swap-window -t -1 \; select-window -t -1
bind -n C-M-l swap-window -t +1 \; select-window -t +1

# use table to bind to two keys
bind c new-window -c "#{pane_current_path}" -n "#{b:pane_current_path}"
bind w switch-client -T window_table
bind -T window_table s split-window -v -c "#{pane_current_path}"
bind -T window_table v split-window -h -c "#{pane_current_path}" \; resize-pane -x 30%
bind -T window_table f choose-tree
bind -T window_table r command-prompt -I "#W" { rename-window "%%" }
bind -T window_table w rename-window "#{b:pane_current_path}"
bind -T window_table d kill-window
bind -T window_table L swap-pane -U
bind -T window_table H swap-pane -D
bind -T window_table n new-window -c "#{pane_current_path}"

bind p switch-client -T pane_table
bind -T pane_table r command-prompt -I "#W" { select-pane -T "%%" }
bind -T pane_table w break-pane
bind -T pane_table d kill-pane
bind -T pane_table x swap-pane -D
bind -T pane_table l display-menu -T "Select Layout" \
    "Tiled"              "" "select-layout tiled" \
    "Even Horizontal"    "" "select-layout even-horizontal" \
    "Even Vertical"      "" "select-layout even-vertical" \
    "Main Horizontal"    "" "select-layout main-horizontal" \
    "Main Vertical"      "" "select-layout main-vertical"
bind h resize-pane -Z # leader-h to toggle pane zoom


bind -n C-y copy-mode


# Easy config reload
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config sourced"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-open'
set -g @plugin 'kristijan/fzf-pane-switch.tmux'

set -g @plugin 'egel/tmux-gruvbox'
# set desired theme options...
set -g @tmux-gruvbox 'dark256'
set-option -g status-position top


# copy like in vim
set-option -g mode-keys vi
# set-window-option -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel
# # INFO: hack to prevent wrapped text new lines
# bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel "tr -d '\n' | pbcopy"


run '~/.tmux/plugins/tpm/tpm'

set -g pane-border-format "#{pane_title} > #{pane_current_command}"
set -g pane-border-status top
set -g pane-border-lines double

